version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_manager_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./task_manager
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && rails s -b '0.0.0.0'"
    volumes:
      - "./task_manager:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db

  auth_service:
    build: ./auth_service
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && rails s -b '0.0.0.0'"
    ports:
      - "3001:3001"
    depends_on:
      - db

  notifications_service:
    build: ./notifications_service
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && rails s -b '0.0.0.0'"
    ports:
      - "3002:3002"
    depends_on:
      - db

  scraping_service:
    build: ./scraping_service
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && rails s -b '0.0.0.0'"
    ports:
      - "3003:3003"
    depends_on:
      - db

volumes:
  db_data:
