default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_production
  username: task_manager
  password: <%= ENV['TASK_MANAGER_DATABASE_PASSWORD'] %>
